---
galaxy_info:
  role_name: docker
  namespace: len-iot
  author: DevOps Team
  description: Ansible role to prepare and deploy Docker on Ubuntu 24.04 target hosts.
  company: PT Len IOT

  license: GPL-3.0-only

  min_ansible_version: "2.15"

  platforms:
    - name: Ubuntu
      versions:
        - noble

  galaxy_tags:
    - docker
    - container
    - containerd
    - buildx
    - compose

dependencies: []
