- name: Check if docker network exists
  community.docker.docker_network:
    name: "{{ cms_network_name }}"
    state: present

- name: Create directory for prometheus configuration
  ansible.builtin.file:
    path: /etc/prometheus
    state: directory
    mode: "0755"

- name: Render prometheus.yml
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    mode: "0644"
  notify: restart prometheus

- name: Create directory for monitoring stack
  ansible.builtin.file:
    path: /opt/monitoring
    state: directory
    mode: "0755"

- name: Render docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /opt/monitoring/docker-compose.yml
    mode: "0644"

- name: Running monitoring stack via docker-compose
  community.docker.docker_compose_v2:
    project_src: /opt/monitoring
    state: present
